# Generated by Django 5.2.10 on 2026-01-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnt', '0003_plantdisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('common_name', models.CharField(max_length=200, null=True)),
                ('scientific_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=600, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=200, null=True)),
                ('prop_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plnt.plantcare')),
            ],
        ),
    ]
