# Generated by Django 5.2.10 on 2026-01-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnt', '0004_plantcare_plantproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcare',
            name='reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plnt.registration'),
        ),
    ]
