# Generated by Django 5.2.10 on 2026-01-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnt', '0005_plantcare_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcare',
            name='care_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantproperties',
            name='prop_care',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='plnt.plantcare'),
        ),
    ]
