# Generated by Django 5.2.10 on 2026-01-17 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnt', '0006_plantcare_care_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimage',
            name='reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plnt.registration'),
        ),
    ]
