# Generated by Django 5.2.10 on 2026-01-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnt', '0007_plantimage_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimage',
            name='common_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='scientific_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
