# Generated by Django 5.2.10 on 2026-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnt', '0008_plantimage_common_name_plantimage_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
