# Generated by Django 5.2.10 on 2026-01-18 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnt', '0010_tempplantimage_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdisease',
            name='reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plnt.registration'),
        ),
    ]
