# Generated by Django 5.2.10 on 2026-01-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnt', '0011_plantdisease_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reminder_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plnt.registration')),
            ],
        ),
    ]
