# Generated by Django 5.2.10 on 2026-01-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnt', '0012_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdisease',
            name='plant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
