# Generated by Django 5.2.10 on 2026-01-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnt', '0013_plantdisease_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCareComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plnt.plantcare')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plnt.registration')),
            ],
        ),
        migrations.CreateModel(
            name='PlantCareSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='plnt.plantcare')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plnt.registration')),
            ],
        ),
        migrations.CreateModel(
            name='PlantCareLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='plnt.plantcare')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plnt.registration')),
            ],
            options={
                'unique_together': {('care', 'reg')},
            },
        ),
    ]
