# Generated by Django 5.2.10 on 2026-01-26 10:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnt', '0014_plantcarecomment_plantcaresave_plantcarelike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plnt.registration'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
